// From https://www.fantasynamegenerators.com/planet-names.php
const planetNames = [
  "Yizueruta",
  "Vumuvis",
  "Numore",
  "Vugnilia",
  "Riatune",
  "Puria",
  "Nuzulia",
  "Devutis",
  "Thone 8FN",
  "Pherth EZ",
  "Hizehines",
  "Idroilia",
  "Ralverth",
  "Paphorix",
  "Ocarro",
  "Deithea",
  "Grakatera",
  "Phomulara",
  "Voria 2A",
  "Sadus EKHQ",
  "Dugagawa",
  "Chobritera",
  "Seccoria",
  "Xingypso",
  "Yianus",
  "Eria",
  "Crilugawa",
  "Gnobulia",
  "Thorix I9",
  "Ciri 4W7H",
  "Adruavis",
  "Gizuter",
  "Mineron",
  "Penzeshan",
  "Chebos",
  "Thaithea",
  "Banuter",
  "Vugirilia",
  "Vion SJ0L",
  "Linda 694",
  "Kisonus",
  "Basanope",
  "Estrore",
  "Zucilles",
  "Eutis",
  "Zunope",
  "Zovonerth",
  "Nacuphus",
  "Stryria O3",
  "Gnorix QY5",
  "Tilitis",
  "Elmeonus",
  "Igerth",
  "Panveron",
  "Chuiclite",
  "Iezuno",
  "Sacharuta",
  "Cionerth",
  "Dinda KOS",
  "Dreon S5M3",
  "Resahiri",
  "Zalvuecarro",
  "Lichiuq",
  "Ilrilles",
  "Ciohines",
  "Caestea",
  "Cayunov",
  "Luzephus",
  "Mapus 3I3X",
  "Tragua BF",
  "Vundoizuno",
  "Lacobos",
  "Evone",
  "Ilnorix",
  "Ecarro",
  "Yarus",
  "Crurelea",
  "Soitera",
  "Strorth 7O56",
  "Gradus 613",
  "Onuihines",
  "Adruarilia",
  "Ullion",
  "Kigyria",
  "Veonov",
  "Xaicarro",
  "Pheticarro",
  "Lagotania",
  "Thov 739",
  "Brone 47L6",
  "Ilmaeruta",
  "Xavelia",
  "Kanzore",
  "Yilora",
  "Xalea",
  "Heoruta",
  "Nitaphus",
  "Phooter",
  "Brorth 5Q1",
  "Sagua MEK",
];

export const getPlanetName = (): string =>
  planetNames[Math.min(Math.ceil(Math.random() * planetNames.length), planetNames.length - 1)];
